### ISSUE TITLE
Support snapshotting SUT

### ISSUE THREAD

**Issue by jantman** [puppetlabs/beaker#393]
It would be *really* nice to be able to snapshot SUTs. There's a Vagrant plugin for VirtualBox that does it quite nicely, though I haven't tried the cross-provider ones.

I *think* that the ideal implementation for me would be to just let the user handle all of it, i.e. simply expose the functionality via the DSL and let me, in my tests, ``take_snapshot(:step1)`` and ``restore_snapshot(:step1)``.

I know it's a pretty big undertaking and I hate submitting issues that I have little to no intent of trying to fix, but this came up when I was trying to test https://github.com/puppetlabs/puppetlabs-rabbitmq/pull/221 (where the package simply can't be cleanly upgraded/downgraded).

**Comment by alexjfisher** [comment]
My use case is testing roles.  I followed http://tech.opentable.co.uk/blog/2014/09/01/testing-puppet-with-beaker-pt-dot-3-testing-roles/ but then wanted a way to reset my test environment between tests.

**Comment by anodelman** [comment]
https://github.com/puppetlabs/beaker/pull/654 closed due to inactivity.

**Comment by jantman** [comment]
So this is just off the table?
