### ISSUE TITLE
Adding a utility method for adding host entries  

### ISSUE THREAD

**Issue by liamjbennett** [puppetlabs/beaker#429]
As much as this is a infrastructure-smell in the linux world, adding
hosts entries is still all to common in the windows world. This method
allows host entries to be configured to meet that need.

It can also be used when developing with vagrant to make sure that the
master and agent vms can see each other properly.

**Comment by anodelman** [comment]
Is this till required?  I have a suspicion that something like this was merged.

**Comment by liamjbennett** [comment]
I don't think this is need any more. It has been some time since I have looked at this. Happy to close this for now and re-open if the issue arises again.
