### ISSUE TITLE
add-el-extras (and possibly other CLI options) not accessible via DSL

### ISSUE THREAD

**Issue by jantman** [puppetlabs/beaker#447]
There doesn't seem to be an intuitive way to use the add_el_extras method to install EPEL through the DSL or through the spec_helper - it appears to only be a command line option (--add-el-extras).

This would be really useful to have accessible at least via the spec_helper like install_puppet, or via the DSL.

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-12
