### ISSUE TITLE
additional aws_sdk configuration support

### ISSUE THREAD

**Issue by adamjk-dev** [puppetlabs/beaker#481]
It would be great to have a vagrant_aws provider as well. The new hypervisor type would use the vagrant-aws plugin and allow setting VPCs, IP addresses, security groups, keypairs, tags, and everything to build up a customizable Vagrantfile that would be used by beaker.

**Comment by adamjk-dev** [comment]
Any status on this?

**Comment by anodelman** [comment]
I'm afraid that our JIRA bugs are not available for public viewing.  This is a low priority and is unlikely to be fixed in the next few months.

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-13
