### ISSUE TITLE
uninitialized constant MiniTest

### ISSUE THREAD

**Issue by amgrice** [puppetlabs/beaker#484]
Hello there,

I have run into an issue when trying to execute beaker with any flags I get a NameError from MiniTest. I've experienced this on two machines now with gems that are up to date. I'm running OS X 10.9.5 with ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]. Not super great at tracking down issues yet in Ruby, but here is a link to a gist with the error and list of installed gems: https://gist.github.com/amgrice/f6a2a09f6baabea0d2ca

**Comment by anodelman** [comment]
Minitest was upgraded with the deprecation of ruby 1.8.  I believe that this issue is resolved.
