### ISSUE TITLE
Add Digital Ocean hypervisor

### ISSUE THREAD

**Issue by petems** [puppetlabs/beaker#499]
DO instances are fairly cheap and easy to setup, would make a good hypervisor for Beaker tests. 

Probably using API hooks from https://github.com/boats/barge

I'll give it a go and see how much I can pull in from the other hypervisor code :+1:

**Comment by anodelman** [comment]
Any progress here?

**Comment by petems** [comment]
I did some basic spiking over the weekend but nothing solid.

**Comment by petems** [comment]
Ok, I've got two implementations:

One uses Fog in it's own hypervisor, works fine, I'm fixing up the commits now.

However, after I was done I realised that a generic Fog handler would be wayyyyyyy better and extendable. As Fog has support for a lot of cloud providers, it means we could just use one provider rather than having to create a new hypervisor each time someone has a new VPS they want to add.

**Comment by anodelman** [comment]
From an internal discussion we will not be supporting additional hypervisors that we do not use internally.  We are willing to looking at the vagrant-fog work as a means to easier use of additional virtualization options for others.  Closing, wontfix.

**Comment by petems** [comment]
Ended up being implemented in: https://github.com/petems/beaker-fog

Will write up a Wiki guide on how to do it in the future, will probably mean we can close up a lot of the PR's to add in new Hypervisors that Puppetlabs is not going to use :+1:
