### ISSUE TITLE
box_check_update is incompatible with Vagrant 1.4

### ISSUE THREAD

**Issue by raphink** [puppetlabs/beaker#523]
When running beaker with Vagrant 1.4, Vagrant cannot start the machines due to an unknown configuration stanza:

```
vm:
* The following settings shouldn't exist: box_check_update
```

**Comment by anodelman** [comment]
This needs to be filed internally for tracking.

**Comment by anodelman** [comment]
Filed internally, assigned to @sschneid.

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-15
