### ISSUE TITLE
Problem with vSphere Hypervisor, rvc + nokogiri

### ISSUE THREAD

**Issue by GeorgFoc** [puppetlabs/beaker#527]
Hi,
I want to use Beaker with vSphere Hypervisor. But wenn run my test, I get:

Failed: errored in CLI.provision                                            
RuntimeError: unknown VMODL type AnyType

After some searching, I found, that this is a problem with rvc and nokogiri 1.5.11
The workaround that vmware recommends is to downgrade to nokogiri 1.5.5. With this version the "unknown VMODL" error is gone.
But beaker needs nokogiri 1.5.11 and so I cannot use beaker with vsphere, or is there an other workaround. 

Hier some facts:
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
beaker 1.20.1
beaker-spec 3.0.0
rvc 1.8.0
rbvmomi 1.8.1
vCenter : 5.5.0.20200 Build 2183109

Thanks

**Comment by anodelman** [comment]
Closing since we updated our pins in beaker 2+
