### ISSUE TITLE
Allow generic configuration of Vagrantfile from hosts config file.

### ISSUE THREAD

**Issue by justinstoller** [puppetlabs/beaker#533]
For specific instances of features requested see:

Configuring plugins:
https://github.com/puppetlabs/beaker/issues/458
Disabling plugins:
https://github.com/puppetlabs/beaker/issues/320
Configuring port forwarding:
https://github.com/puppetlabs/beaker/issues/504

Until the beaker tickets are moved to their own tracker and made public (QENG-1483) this is a public copy of QENG-1481.

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-16
