### ISSUE TITLE
beaker should utilize the .fixtures file to populate modules directory on the SUT

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/beaker#550]
I think we should make beaker work in a similar fashion to puppetlabs_spec_helper/rspec-puppet with regards to the fixtures directory.  For example with running unit tests with puppet `rake spec` the first order of business is to create a fixtures modules directory that the tests will use.  This modules directory contains all the dependency modules that your module uses and instructs the puppetlabs_spec_helper how to download them.  When the catalog is built it uses this fixtures modules directory to find all the puppet code.

The beaker workflow should utilize the same .fixtures file to download all the modules for the SUT to use.

A typical pattern is to perform the following "puppet module install" of several dependent modules in the spec helper:

```
c.before :suite do
    # Install module and dependencies
    puppet_module_install(:source => proj_root, :module_name => 'mysql')
    hosts.each do |host|
      # Required for binding tests.
      if fact('osfamily') == 'RedHat'
        version = fact("operatingsystemmajrelease")
        shell("yum localinstall -y http://yum.puppetlabs.com/puppetlabs-release-el-#{version}.noarch.rpm")
        if fact('operatingsystemmajrelease') =~ /7/ || fact('operatingsystem') =~ /Fedora/
          shell("yum install -y bzip2")
        end
      end

      shell("/bin/touch #{default['puppetpath']}/hiera.yaml")
      shell('puppet module install puppetlabs-stdlib --version 3.2.0', { :acceptable_exit_codes => [0,1] })
      on host, puppet('module','install','stahnma/epel'), { :acceptable_exit_codes => [0,1] }
    end
  end
```

With this in mind I feel like we are duplicating the .fixtures file and listing our dependencies twice (once for unit tests, and then for beaker tests).

This could easily be done by creating some helper code to process the fixtures files and run puppet(module, install, xxx) on all of the dependencies or better to just share the fixtures directory on the SUT system.  This would reduce testing time because the modules would not need to be downloaded for each SUT

**Comment by anodelman** [comment]
Could you link up to the ticket that you filed?

**Comment by logicminds** [comment]
I have not filed a jira ticket as I don't know exactly where it should and under which project. I will go ahead with adding this feature to puppet labs_spec_helper but I think we should additionally have the conversation internally to make "one file to rule them all".

**Comment by anodelman** [comment]
If a bigger conversation needs to be had it isn't in this issue. :)  I'm going to close this out as there are not current changes required for beaker or beaker-rspec.  Please discuss changes to puppetlabs spec helper in #puppet-dev on freenode.  Ping @hunner.
