### ISSUE TITLE
Using platform 'redhat' fails with 'Package curl cannot be queried'

### ISSUE THREAD

**Issue by nemski** [puppetlabs/beaker#570]
The RedHat naming convention is inconsistent The documentation refers to RedHat Enterprise Linux as simply "redhat" and the platform code accepts 'redhat' and 'el' as possible values to define it but various code, including unix/pkg.rb only look for the 'el' platform and fail when a platform of 'redhat' is provided.

The name 'el' isn't really descriptive. My preference would be to gut all references to redhat and el and only use the platform of 'rhel' to avoid having to cater for duplicate names while keeping it descriptive.

**Comment by anodelman** [comment]
There is definitely confusion in the code.  We settled on using 'el-' exclusively, but won't crash if you happen to call something rhel or centos (we just don't treat them properly).  It is unlikely that I can do a full renaming run due to all of our internal dependencies, would extending to el-/redhat/centos be better?

**Comment by nemski** [comment]
I think the easiest option would be just to change the documentation to tell users to specify "el-" for centos/redhat. Supporting el-/redhat/centos will also solve it.

**Comment by anodelman** [comment]
Sounds reasonable.  I'll get that filed internally.

**Comment by anodelman** [comment]
I have updated the documentation to indicate only el- as a supported platform name.  I would also like to get stricter enforcement in beaker itself.

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-17
