### ISSUE TITLE
Beaker fails with vagrant 1.7.x

### ISSUE THREAD

**Issue by chris-reeves** [puppetlabs/beaker#585]
When beaker 2.0.0 is used with vagrant 1.7.x, it fails when trying to configure the vagrant boxes (unable to connect via ssh):

> ...
> configure vagrant boxes (set ssh-config, switch to root user, hack etc/hosts)
> Give root a copy of current user's keys, on ubuntu-server-1404-x64
> 
> ubuntu-server-1404-x64 11:08:32$ sudo su -c "cp -r .ssh /root/."
> Warning: Try 1 -- Host 10.255.36.184 unreachable: Authentication failed for user vagrant@127.0.0.1
> Warning: Trying again in 1 seconds
> Warning: Try 2 -- Host 10.255.36.184 unreachable: Authentication failed for user vagrant@127.0.0.1
> Warning: Trying again in 1 seconds
> Warning: Try 3 -- Host 10.255.36.184 unreachable: Authentication failed for user vagrant@127.0.0.1
> Warning: Trying again in 2 seconds
> Warning: Try 4 -- Host 10.255.36.184 unreachable: Authentication failed for user vagrant@127.0.0.1
> Warning: Trying again in 3 seconds
> ...

This is because, as of version 1.7.x, vagrant will replace the default insecure keypair with a randomly generated keypair on first `vagrant up`. As a result the generated ssh configs have changed and contain per-host private keys.

Typical output from `vagrant ssh-config` for vagrant 1.6.x:
> Host ubuntu-server-1404-x64
>   HostName 127.0.0.1
>   User vagrant
>   Port 2222
>   UserKnownHostsFile /dev/null
>   StrictHostKeyChecking no
>   PasswordAuthentication no
>   IdentityFile /home/user/.vagrant.d/insecure_private_key
>   IdentitiesOnly yes
>   LogLevel FATAL

Typical output from `vagrant ssh-config` for vagrant 1.7.x:
> Host ubuntu-server-1404-x64
>   HostName 127.0.0.1
>   User vagrant
>   Port 2222
>   UserKnownHostsFile /dev/null
>   StrictHostKeyChecking no
>   PasswordAuthentication no
>   IdentityFile /home/user/test-project/.vagrant/beaker_vagrant_files/default.yml/.vagrant/machines/ubuntu-server-1404-x64/virtualbox/private_key
>   IdentitiesOnly yes
>   LogLevel FATAL

Beaker breaks the path to these new private key files when creating its own local copy due to a substitution which is not sufficiently constrained (the path to the private key now also contains the hostname, which was being replaced with the host's IP).

**Comment by anodelman** [comment]
Merged.

Released in beaker 2.2.
