### ISSUE TITLE
Enable SSH agent forwarding for Vagrant and Docker

### ISSUE THREAD

**Issue by madAndroid** [puppetlabs/beaker#587]
During my testing on Jenkins, I've discovered that Docker containers are accessed by Beaker without any ssh agent forwarding enabled; as a result, connections to Github using the Jenkins ssh-agent plugin are failing. I test locally in vagrant, and it looks as though the Vagrantfile being generated doesn't have agent forwarding enabled either, so my testing fails locally as well.

**Comment by anodelman** [comment]
Closed, merged.
