### ISSUE TITLE
puppet-server support

### ISSUE THREAD

**Issue by electrical** [puppetlabs/beaker#594]
Hi all,

are there plans to implement support for running tests with puppet-server and beaker?
Or is that support already there and am i just completely blind?
reason for asking is that an issue was reported [0] on my Logstash module.
Thanks

[0] https://github.com/elasticsearch/puppet-logstash/issues/193

**Comment by anodelman** [comment]
I'm going to have to do more investigation here and get back to you.

**Comment by waynr** [comment]
@electrical 
We do test puppet-server using beaker.

Unfortunately the state of documentation for acceptance testing puppet-server is somewhat poor but we are aware of the need to improve it and have it scoped in upcoming work:
https://tickets.puppetlabs.com/browse/SERVER-317

This is our current documentation:
https://github.com/puppetlabs/puppet-server/blob/master/acceptance/README.md

We'd really appreciate any feedback or improvements you might have to suggest :)

**Comment by anodelman** [comment]
Closing this out, you can follow up through the doc and to @waynr .
