### ISSUE TITLE
Easier way to find generated Vagrantfile

### ISSUE THREAD

**Issue by pizzaops** [puppetlabs/beaker#609]
Maybe at this step—

```
Beaker::Hypervisor, found some vagrant boxes to create
created Vagrantfile for VagrantHost centos-64-x64
Bringing machine 'centos-64-x64' up with 'virtualbox' provider...
```

—it could output the path?

I find myself doing a lot of `find ./ -name Vagrantfile`

**Comment by anodelman** [comment]
Will file a matching internal bug for tracking.

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-18
