### ISSUE TITLE
Wait for DNS Resolution in vcloud hypervisor

### ISSUE THREAD

**Issue by frizop** [puppetlabs/beaker#628]
I'm having a bit of a problem with how a few things happen on the `vcloud` hypervisor. One of them is that in the `wait_for_dns_resolution` method assumes a few things, it assumes that the hostname is the exact same as the VM name, and it assumes that the beaker server (or box executing beaker) is on the same DNS Suffix

On a vsphere environment that means that you're going to run a customization spec so that the hostname of the machine gets replaced. By itself this is fine, but when combined with a server executing beaker on a different DNS Suffix the process falls over.

I propose that we use the virtual machine hostname as defined by vmware tools to pull this information. This runs into another issue though, the `Class SshConnection` currently uses the short dns name (ie: machine name) to connect, via the following: hosts.rb:95 `self['ip'] || hostname` found in the method `reachable_name` 

This sort of boils down to this: on the one hand I have the information for vSphere/vCloud to properly connect to the node, but there is no interface for me to pass this along to the `Class SshConnection`. This would make things better for the vSphere side. On the other hand this doesn't improve anything outside of the vSphere/vCloud hypervisor; unless I'm missing something?

**Comment by anodelman** [comment]
Looking things over hostname is:

      @defaults['vmhostname'] || @name

So we are referring to the vmhostname here and not the name as defined in the beaker host configuration file.

I may just be confused as to what test you are trying to run with with configuration file.  Could you give me some logs/more info?

**Comment by frizop** [comment]
So in this case, both `vmhostname` and `name` are just the dns short name, so a random string of characters without a suffix of any sort.

Logs: http://pastebin.com/nnfSwpx4

At the end of the log, you can see if I tag the suffix I can make the request, I could also ask the vmware tools what my hostname is and get the full dns name (with suffix)

**Comment by anodelman** [comment]
Hm, I'd be interested to test this internally.  Using the name provided by vmware does sound like a good idea but it may affect our multi-node puppet autoinstallation scripts.

**Comment by frizop** [comment]
Just for clarification, I've rewritten the `wait_for_dns_resolution` in the vcloud.rb hypervisor to also wait for the tools to report the same as the dns name, because again - you're going to be using a Customization Spec if you're using vcloud.rb, I can offer this as a PR, but it doesn't solve the `SshConnection` class as I've felt touching it would be out of scope. I can also include a PR for find_datastore, find_folder, and find_pool which include looking for the config option datacenter: foo, because all of these environments require a datacenter which is not the first listed. Though, I feel like this should be a separate PR and might require a bit of counsel. 

Since doing this though we've decided to use vsphere hypervisor as the issues we were having with Post Domain Join (due to a lack of proper dns registration) were too costly in man hours.

**Comment by anodelman** [comment]
I think that submitting PRs would be appropriate.

Please file appropriate bugs here:

https://tickets.puppetlabs.com/issues/?jql=project%20%3D%20BKR
