### ISSUE TITLE
[docker] Execute commands with docker exec instead of ssh

### ISSUE THREAD

**Issue by carlossg** [puppetlabs/beaker#641]
The docker provider is installing extra packages and configs, opening ports, etc just to be able to execute commands in the test box.
I have done some work on using docker exec instead, it's fairly simple for executing commands.
Downloading files from the container can be done with `docker cp`, and the tricky part is to push files to the container, should use volumes or something else.

I'm opening this issue to gather some feedback or interest before moving forward

**Comment by electrical** [comment]
the problem with docker exec is that it works in some use cases. when managing services like i do with the Elasticsearch Puppet module it will fail be cause the container is then not actually running.
Also it would make docker the ugly duck of all the hypervisors for doing things extremely different compared to all the others.

**Comment by carlossg** [comment]
When you say 'doing things different', you mean easier? :)

If you are testing services you should do your thing with your container definition, ensure services can run and so, but there are tons of modules that don't touch services at all, and downloading and installing ssh it's just a waste of time

**Comment by electrical** [comment]
If the base image needs to download and install ssh then the base image is wrong :-)
I have built custom images that contain everything so i can run my tests very fast.

Also an other thing is that serverspec/specinfra requires ssh to work :-)

**Comment by carlossg** [comment]
Well' it's just that most Docker images will not include ssh, definitely not the official ones for the different Linux flavors.
The serverspec/specinfra point is a good one :|

**Comment by anodelman** [comment]
Moving to a different communication technique only for docker is not a viable options - we'd have to split out all of the beaker provided built in methods to handle two different execution methods.  Beaker is built with the underlying assumption that you can passwordlessly ssh as root to all test nodes.  Breaking that assumption will pretty much break the system.
