### ISSUE TITLE
Windows SUT - issues getting started

### ISSUE THREAD

**Issue by frizop** [puppetlabs/beaker#650]
I basically pulled down puppetlabs/stdlib extracted `spec_helper_acceptance.rb`, `abs_spec.rb` and am trying to test them against a windows server I built. I installed cygwin, openssh, etc. SSH Seems to connect just fine, but for some reason I'm getting this method failure `#<NoMethodError: undefined method 'backend=' for #<RSpec::Core::Configuration:0x007ff94ac519d0>>`

Really not sure why, figure something is wrong with the box setup, this is against a vSphere enviornment. 

@anodelman asked me to open this after reading the painful except from #puppet-dev @ freenode.

Let me know if there is anything else I can post to help divide and conquer. 
   
    [frizop@profail]~/Documents/src/puppet/vagrant-windows/site/git% bundler exec beaker -h spec/acceptance/nodesets/default.yml --debug --tests spec/acceptance/abs_spec.rb --load-path spec
    {
        "project": "Beaker",
        "department": "unknown",
        "created_by": "frizop",
        "jenkins_build_url": null,
        "validate": true,
        "configure": true,
        "log_level": "debug",
        "trace_limit": 10,
        "master-start-curl-retries": 120,
        "options_file": null,
        "type": "pe",
        "provision": true,
        "preserve_hosts": "never",
        "root_keys": false,
        "quiet": false,
        "project_root": "/Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker",
        "xml_dir": "junit",
        "xml_file": "beaker_junit.xml",
        "xml_stylesheet": "junit.xsl",
        "log_dir": "log",
        "color": true,
        "dry_run": false,
        "timeout": 600,
        "fail_mode": "slow",
        "accept_all_exit_codes": false,
        "timesync": false,
        "disable_iptables": false,
        "repo_proxy": false,
        "package_proxy": false,
        "add_el_extras": false,
        "release_apt_repo_url": "http://apt.puppetlabs.com",
        "release_yum_repo_url": "http://yum.puppetlabs.com",
        "dev_builds_url": "http://builds.delivery.puppetlabs.net",
        "epel_url": "http://mirrors.kernel.org/fedora-epel",
        "epel_arch": "i386",
        "epel_6_pkg": "epel-release-6-8.noarch.rpm",
        "epel_5_pkg": "epel-release-5-4.noarch.rpm",
        "consoleport": 443,
        "pe_dir": "/opt/enterprise/dists",
        "pe_version_file": "LATEST",
        "pe_version_file_win": "LATEST-win",
        "host_env": {},
        "ssh_env_file": "~/.ssh/environment",
        "answers": {
            "q_puppet_enterpriseconsole_auth_user_email": "admin@example.com",
            "q_puppet_enterpriseconsole_auth_password": "~!@#$%^*-/ aZ",
            "q_puppet_enterpriseconsole_smtp_port": 25,
            "q_puppet_enterpriseconsole_smtp_use_tls": "n",
            "q_verify_packages": "y",
            "q_puppetdb_password": "~!@#$%^*-/ aZ",
            "q_puppetmaster_enterpriseconsole_port": 443,
            "q_puppet_enterpriseconsole_auth_database_name": "console_auth",
            "q_puppet_enterpriseconsole_auth_database_user": "mYu7hu3r",
            "q_puppet_enterpriseconsole_database_name": "console",
            "q_puppet_enterpriseconsole_database_user": "mYc0nS03u3r",
            "q_database_root_password": "=ZYdjiP3jCwV5eo9s1MBd",
            "q_database_root_user": "pe-postgres",
            "q_database_export_dir": "/tmp",
            "q_puppetdb_database_name": "pe-puppetdb",
            "q_puppetdb_database_user": "mYpdBu3r",
            "q_database_port": 5432,
            "q_puppetdb_port": 8081,
            "q_classifier_database_user": "DFGhjlkj",
            "q_database_name": "pe-classifier",
            "q_classifier_database_password": "~!@#$%^*-/ aZ",
            "q_activity_database_user": "adsfglkj",
            "q_activity_database_name": "pe-activity",
            "q_activity_database_password": "~!@#$%^*-/ aZ",
            "q_rbac_database_user": "RbhNBklm",
            "q_rbac_database_name": "pe-rbac",
            "q_rbac_database_password": "~!@#$%^*-/ aZ"
        },
        "dot_fog": "/Users/frizop/.fog",
        "ec2_yaml": "config/image_templates/ec2.yaml",
        "help": false,
        "collect_perf_data": false,
        "ssh": {
            "config": false,
            "paranoid": false,
            "timeout": 300,
            "auth_methods": [
                "publickey"
            ],
            "port": 22,
            "forward_agent": true,
            "keys": [
                "/Users/frizop/.ssh/id_rsa"
            ],
            "user_known_hosts_file": "/Users/frizop/.ssh/known_hosts"
        },
        "hosts_file": "spec/acceptance/nodesets/default.yml",
        "tests": [
            "spec/acceptance/abs_spec.rb"
        ],
        "load_path": [
            "spec"
        ],
        "command_line": "/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bin/beaker -h spec/acceptance/nodesets/default.yml --debug --tests spec/acceptance/abs_spec.rb --load-path spec",
        "HOSTS": {
            "10.47.8.90": {
                "roles": [
                    "master",
                    "default"
                ],
                "platform": "el-6-x86_64",
                "vmname": "t-l-rhel6",
                "snapshot": "cool",
                "hypervisor": "vsphere",
                "datacenter": "USFOO"
            },
            "craftedpap.foo.lan": {
                "roles": [
                    "agent"
                ],
                "platform": "windows-6-x64",
                "vmname": "t-w-2k12",
                "snapshot": "cool3",
                "hypervisor": "vsphere",
                "datacenter": "USFOO"
            }
        },
        "datastore": "USR-PODE-00-203",
        "folder": "PO/DevOps/TeamCity/Test Boxes",
        "resourcepool": "PodE/Resources",
        "home": "/Users/frizop",
        "helper": [],
        "pre_suite": [],
        "post_suite": [],
        "install": [],
        "modules": [],
        "logger": "#<Beaker::Logger:0x007ff94951bc20>",
        "timestamp": "2015-01-27 17:04:54 -0800"
    }
    Hypervisor for 10.47.8.90 is vsphere
    Hypervisor for craftedpap.foo.lan is vsphere
    Beaker::Hypervisor, found some vsphere boxes to create
    Connecting to vSphere at USFOO-svcenter.foo.lan with credentials for foo.lan\foo
    {:HOSTS=>{:"10.47.8.90"=>{:roles=>["master"], :platform=>"el-6-x86_64", :vmname=>"t-l-rhel6", :snapshot=>"cool", :hypervisor=>"vsphere", :datacenter=>"USFOO"}, :"craftedpap.foo.lan"=>{:roles=>["agent"], :platform=>"windows-6-x64", :vmname=>"t-w-2k12", :snapshot=>"cool3", :hypervisor=>"vsphere", :datacenter=>"USFOO"}}, :consoleport=>443, :datastore=>"USR-PODE-00-203", :folder=>"PO/DevOps/TeamCity/Test Boxes", :resourcepool=>"PodE/Resources", :timeout=>600}
    Reverting t-l-rhel6 to snapshot 'cool'
    Spent 1.05 seconds reverting
    Booting t-l-rhel6
    Spent 9.78 seconds booting t-l-rhel6
    Reverting t-w-2k12 to snapshot 'cool3'
    Spent 7.95 seconds reverting

    10.47.8.90 17:05:17$ rpm -q curl
    Created ssh connection to 10.47.8.90, user: root, opts: {:config=>false, :paranoid=>false, :timeout=>300, :auth_methods=>["publickey"], :port=>22, :forward_agent=>true, :keys=>["/Users/frizop/.ssh/id_rsa"], :user_known_hosts_file=>"/Users/frizop/.ssh/known_hosts", :user=>"root"}
    curl-7.19.7-37.el6_5.3.x86_64

    10.47.8.90 executed in 36.14 seconds

    10.47.8.90 17:05:53$ rpm -q ntpdate
    ntpdate-4.2.6p5-1.el6.x86_64

    10.47.8.90 executed in 0.09 seconds

    craftedpap.foo.lan 17:05:53$ cygcheck curl
    Created ssh connection to craftedpap.foo.lan, user: Administrator, opts: {:config=>false, :paranoid=>false, :timeout=>300, :auth_methods=>["publickey"], :port=>22, :forward_agent=>true, :keys=>["/Users/frizop/.ssh/id_rsa"], :user_known_hosts_file=>"/Users/frizop/.ssh/known_hosts", :user=>"Administrator"}
    Found: C:\cygwin\bin\curl.exe
    C:\cygwin\bin\curl.exe
      C:\cygwin\bin\cygcurl-4.dll
        C:\cygwin\bin\cygcrypto-1.0.0.dll
          C:\cygwin\bin\cygwin1.dll
            C:\Windows\system32\KERNEL32.dll
              C:\Windows\system32\api-ms-win-core-rtlsupport-l1-2-0.dll
              C:\Windows\system32\ntdll.dll
              C:\Windows\system32\KERNELBASE.dll
                C:\Windows\system32\api-ms-win-core-apiquery-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-processthreads-l1-1-2.dll
              C:\Windows\system32\api-ms-win-core-registry-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-heap-l1-2-0.dll
              C:\Windows\system32\api-ms-win-core-memory-l1-1-2.dll
              C:\Windows\system32\api-ms-win-core-handle-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-synch-l1-2-0.dll
              C:\Windows\system32\api-ms-win-core-file-l1-2-1.dll
              C:\Windows\system32\api-ms-win-core-delayload-l1-1-1.dll
              C:\Windows\system32\api-ms-win-core-io-l1-1-1.dll
              C:\Windows\system32\api-ms-win-core-job-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-threadpool-legacy-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-threadpool-private-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-libraryloader-l1-2-0.dll
              C:\Windows\system32\api-ms-win-core-namedpipe-l1-2-0.dll
              C:\Windows\system32\api-ms-win-core-datetime-l1-1-1.dll
              C:\Windows\system32\api-ms-win-core-sysinfo-l1-2-1.dll
              C:\Windows\system32\api-ms-win-core-timezone-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-localization-l1-2-1.dll
              C:\Windows\system32\api-ms-win-core-processenvironment-l1-2-0.dll
              C:\Windows\system32\api-ms-win-core-string-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-debug-l1-1-1.dll
              C:\Windows\system32\api-ms-win-core-errorhandling-l1-1-1.dll
              C:\Windows\system32\api-ms-win-core-fibers-l1-1-1.dll
              C:\Windows\system32\api-ms-win-core-util-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-profile-l1-1-0.dll
              C:\Windows\system32\api-ms-win-security-base-l1-2-0.dll
              C:\Windows\system32\api-ms-win-security-appcontainer-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-comm-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-realtime-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-wow64-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-systemtopology-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-processtopology-l1-2-0.dll
              C:\Windows\system32\api-ms-win-core-namespace-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-file-l2-1-1.dll
              C:\Windows\system32\api-ms-win-core-xstate-l2-1-0.dll
              C:\Windows\system32\api-ms-win-core-localization-l2-1-0.dll
              C:\Windows\system32\api-ms-win-core-normalization-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-localization-private-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-sidebyside-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-appcompat-l1-1-1.dll
              C:\Windows\system32\api-ms-win-core-windowserrorreporting-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-console-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-console-l2-1-0.dll
              C:\Windows\system32\api-ms-win-core-psapi-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-psapi-ansi-l1-1-0.dll
              C:\Windows\system32\api-ms-win-core-psapi-obsolete-l1-1-0.dll
          C:\cygwin\bin\cygz.dll
        C:\cygwin\bin\cyggssapi_krb5-2.dll
          C:\cygwin\bin\cygk5crypto-3.dll
            C:\cygwin\bin\cygkrb5support-0.dll
              C:\cygwin\bin\cygintl-8.dll
                C:\cygwin\bin\cygiconv-2.dll
          C:\cygwin\bin\cygkrb5-3.dll
            C:\cygwin\bin\cygcom_err-2.dll
              C:\cygwin\bin\cyggcc_s-seh-1.dll
        C:\cygwin\bin\cygidn-11.dll
        C:\cygwin\bin\cyglber-2-4-2.dll
        C:\cygwin\bin\cygldap-2-4-2.dll
          C:\cygwin\bin\cygsasl2-3.dll
          C:\cygwin\bin\cygssl-1.0.0.dll
        C:\cygwin\bin\cygssh2-1.dll
      C:\cygwin\bin\cygmetalink-3.dll
        C:\cygwin\bin\cygexpat-1.dll

    craftedpap.foo.lan executed in 1.22 seconds

    10.47.8.90 17:05:55$ echo "/opt/puppet/bin"
    /opt/puppet/bin

    10.47.8.90 executed in 0.07 seconds
    setting local environment on 10.47.8.90

    10.47.8.90 17:05:55$ echo '
    PermitUserEnvironment yes' >> /etc/ssh/sshd_config

    10.47.8.90 executed in 0.07 seconds

    10.47.8.90 17:05:55$ /sbin/service sshd restart
    Stopping sshd: [  OK  ]
    Starting sshd: [  OK  ]

    10.47.8.90 executed in 0.25 seconds

    10.47.8.90 17:05:55$ mkdir -p ~/.ssh

    10.47.8.90 executed in 0.07 seconds

    10.47.8.90 17:05:55$ chmod 0600 ~/.ssh

    10.47.8.90 executed in 0.06 seconds

    10.47.8.90 17:05:55$ touch ~/.ssh/environment

    10.47.8.90 executed in 0.06 seconds

    10.47.8.90 17:05:55$ grep -e RUBYLIB=.*\$RUBYLIB ~/.ssh/environment

    10.47.8.90 executed in 0.07 seconds
    Exited: 1

    10.47.8.90 17:05:55$ grep RUBYLIB ~/.ssh/environment

    10.47.8.90 executed in 0.07 seconds
    Exited: 1

    10.47.8.90 17:05:55$ echo "RUBYLIB=$RUBYLIB" >> ~/.ssh/environment

    10.47.8.90 executed in 0.06 seconds

    10.47.8.90 17:05:55$ grep -e PATH=.*\$PATH ~/.ssh/environment

    10.47.8.90 executed in 0.06 seconds
    Exited: 1

    10.47.8.90 17:05:55$ grep PATH ~/.ssh/environment

    10.47.8.90 executed in 0.06 seconds
    Exited: 1

    10.47.8.90 17:05:55$ echo "PATH=$PATH" >> ~/.ssh/environment

    10.47.8.90 executed in 0.06 seconds

    10.47.8.90 17:05:56$ grep -e PATH=.*\/opt\/puppet\/bin ~/.ssh/environment

    10.47.8.90 executed in 0.07 seconds
    Exited: 1

    10.47.8.90 17:05:56$ grep PATH ~/.ssh/environment
    PATH=/opt/staf/bin:/opt/staf:/opt/TeamCity/agent/bin:/usr/java/default/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

    10.47.8.90 executed in 0.07 seconds

    10.47.8.90 17:05:56$ sed -i -e "s/PATH=/PATH=\/opt\/puppet\/bin:/" ~/.ssh/environment

    10.47.8.90 executed in 0.07 seconds

    10.47.8.90 17:05:56$ grep -e RUBYLIB=.* ~/.ssh/environment
    RUBYLIB=

    10.47.8.90 executed in 0.07 seconds

    craftedpap.foo.lan 17:05:56$ echo "/cygdrive/c/Program Files (x86)/Puppet Labs/Puppet Enterprise/bin:/cygdrive/c/Program Files/Puppet Labs/Puppet Enterprise/bin"
    /cygdrive/c/Program Files (x86)/Puppet Labs/Puppet Enterprise/bin:/cygdrive/c/Program Files/Puppet Labs/Puppet Enterprise/bin

    craftedpap.foo.lan executed in 0.07 seconds
    setting local environment on craftedpap.foo.lan

    craftedpap.foo.lan 17:05:56$ echo '
    PermitUserEnvironment yes' >> /etc/sshd_config

    craftedpap.foo.lan executed in 0.07 seconds

    craftedpap.foo.lan 17:05:56$ cygrunsrv -E sshd

    craftedpap.foo.lan executed in 2.20 seconds

    craftedpap.foo.lan 17:05:58$ cygrunsrv -S sshd

    craftedpap.foo.lan executed in 2.18 seconds

    craftedpap.foo.lan 17:06:00$ mkdir -p ~/.ssh

    craftedpap.foo.lan executed in 0.09 seconds

    craftedpap.foo.lan 17:06:00$ chmod 0600 ~/.ssh

    craftedpap.foo.lan executed in 0.08 seconds

    craftedpap.foo.lan 17:06:01$ touch ~/.ssh/environment

    craftedpap.foo.lan executed in 0.08 seconds

    craftedpap.foo.lan 17:06:01$ grep -e RUBYLIB=.*\$RUBYLIB ~/.ssh/environment
    RUBYLIB=$RUBYLIB:

    craftedpap.foo.lan executed in 0.11 seconds

    craftedpap.foo.lan 17:06:01$ grep -e PATH=.*\$PATH ~/.ssh/environment
    PATH=$PATH:/cygdrive/c/Program Files (x86)/Puppet Labs/Puppet Enterprise/bin:/cygdrive/c/Program Files/Puppet Labs/Puppet Enterprise/bin:/bin:/cygdrive/c/STAF/bin:/cygdrive/c/Python27:/cygdrive/c/Python27/Scripts:/cygdrive/c/Perl64/site/bin:/cygdrive/c/Perl64/bin:/cygdrive/c/Program Files (x86)/Groovy/Groovy-1.8.6/bin:/cygdrive/c/Program Files/Java/jdk1.7.0_72/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/MySQL/MySQL Utilities 1.3.5:/cygdrive/c/Program Files (x86)/InstallAnywhere 2014:/cygdrive/c/PROGRA~2/hec/HSSIHY~1:/cygdrive/c/Program Files/TortoiseSVN/bin:/cygdrive/c/sysinternalssuite:/cygdrive/c/Program Files (x86)/Git/cmd:/cygdrive/c/Program Files/MySql/MySql Server 5.6/bin

    craftedpap.foo.lan executed in 0.08 seconds

    craftedpap.foo.lan 17:06:01$ grep -e PATH=.*\/cygdrive\/c\/Program\ Files\ \(x86\)\/Puppet\ Labs\/Puppet\ Enterprise\/bin:\/cygdrive\/c\/Program\ Files\/Puppet\ Labs\/Puppet\ Enterprise\/bin ~/.ssh/environment
    PATH=$PATH:/cygdrive/c/Program Files (x86)/Puppet Labs/Puppet Enterprise/bin:/cygdrive/c/Program Files/Puppet Labs/Puppet Enterprise/bin:/bin:/cygdrive/c/STAF/bin:/cygdrive/c/Python27:/cygdrive/c/Python27/Scripts:/cygdrive/c/Perl64/site/bin:/cygdrive/c/Perl64/bin:/cygdrive/c/Program Files (x86)/Groovy/Groovy-1.8.6/bin:/cygdrive/c/Program Files/Java/jdk1.7.0_72/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/MySQL/MySQL Utilities 1.3.5:/cygdrive/c/Program Files (x86)/InstallAnywhere 2014:/cygdrive/c/PROGRA~2/hec/HSSIHY~1:/cygdrive/c/Program Files/TortoiseSVN/bin:/cygdrive/c/sysinternalssuite:/cygdrive/c/Program Files (x86)/Git/cmd:/cygdrive/c/Program Files/MySql/MySql Server 5.6/bin

    craftedpap.foo.lan executed in 0.08 seconds

    craftedpap.foo.lan 17:06:01$ grep -e RUBYLIB=.* ~/.ssh/environment
    RUBYLIB=$RUBYLIB:

    craftedpap.foo.lan executed in 0.07 seconds

    craftedpap.foo.lan 17:06:01$ grep -e CYGWIN=.*nodosfilewarning ~/.ssh/environment
    CYGWIN=nodosfilewarning

    craftedpap.foo.lan executed in 0.08 seconds
    No tests to run for suite 'pre_suite'
    Begin spec/acceptance/abs_spec.rb
    #<NoMethodError: undefined method `backend=' for #<RSpec::Core::Configuration:0x007ff94ac519d0>>
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/specinfra-2.11.3/lib/specinfra/configuration.rb:42
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/specinfra-2.11.3/lib/specinfra/helper/set.rb:3
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/beaker-rspec-bbf806a4fc12/lib/beaker-rspec/helpers/serverspec.rb:5
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/beaker-rspec-bbf806a4fc12/lib/beaker-rspec/spec_helper.rb:2
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/beaker-rspec-bbf806a4fc12/lib/beaker-rspec/spec_helper.rb:2
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/beaker-rspec-bbf806a4fc12/lib/beaker-rspec.rb:5
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/beaker-rspec-bbf806a4fc12/lib/beaker-rspec.rb:5
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bundler/gems/beaker-rspec-bbf806a4fc12/lib/beaker-rspec.rb:1
    /Users/frizop/Documents/src/puppet/vagrant-windows/site/git/spec/spec_helper_acceptance.rb:2
    /Users/frizop/Documents/src/puppet/vagrant-windows/site/git/spec/spec_helper_acceptance.rb:2
    /Users/frizop/Documents/src/puppet/vagrant-windows/site/git/spec/acceptance/abs_spec.rb:2
    /Users/frizop/Documents/src/puppet/vagrant-windows/site/git/spec/acceptance/abs_spec.rb:2
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker/test_case.rb:120
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker/test_case.rb:120
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/2.1.0/benchmark.rb:294
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker/test_case.rb:117
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker/test_suite.rb:357
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker/test_suite.rb:354
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker/test_suite.rb:354
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker/test_suite.rb:396
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker/cli.rb:151
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/lib/beaker/cli.rb:95
    /Users/frizop/Documents/src/ruby/beaker-2.2.0/bin/beaker:6
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bin/beaker:23
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bin/beaker:23
    Warning: spec/acceptance/abs_spec.rb errored in 0.27 seconds
          Test Suite: tests @ 2015-01-27 17:06:01 -0800

          - Host Configuration Summary -

                  - Test Case Summary for suite 'tests' -
           Total Suite Time: 0.27 seconds
          Average Test Time: 0.27 seconds
                  Attempted: 1
                     Passed: 0
                     Failed: 0
                    Errored: 1
                    Skipped: 0
                    Pending: 0
                      Total: 1

          - Specific Test Case Status -
            
    Failed Tests Cases:
    Errored Tests Cases:
      Test Case spec/acceptance/abs_spec.rb reported: #<NoMethodError: undefined method `backend=' for #<RSpec::Core::Configuration:0x007ff94ac519d0>>
    Skipped Tests Cases:
    Pending Tests Cases:

    Failed: errored in TestSuite: report_and_raise_on_failure
    #<RuntimeError: Failed while running the tests suite>
    No tests to run for suite 'post_suite'
    Cleanup: cleaning up after failed run
    Destroying vsphere boxes
    Connecting to vSphere at USFOO-svcenter.foo.lan with credentials for foo.lan\foo
    {:HOSTS=>{:"10.47.8.90"=>{:roles=>["master"], :platform=>"el-6-x86_64", :vmname=>"t-l-rhel6", :snapshot=>"cool", :hypervisor=>"vsphere", :datacenter=>"USFOO"}, :"craftedpap.foo.lan"=>{:roles=>["agent"], :platform=>"windows-6-x64", :vmname=>"t-w-2k12", :snapshot=>"cool3", :hypervisor=>"vsphere", :datacenter=>"USFOO"}}, :consoleport=>443, :datastore=>"USR-PODE-00-203", :folder=>"PO/DevOps/TeamCity/Test Boxes", :resourcepool=>"PodE/Resources", :timeout=>600}
    Shutting down t-l-rhel6
    Spent 1.16 seconds halting t-l-rhel6
    Shutting down t-w-2k12
    Spent 1.96 seconds halting t-w-2k12

    You can reproduce this run with:
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bin/beaker -h spec/acceptance/nodesets/default.yml --debug --tests spec/acceptance/abs_spec.rb --load-path spec

    Important ENV variables that may have affected your run:
        GEM_HOME		/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0
        GEM_PATH		/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0:/Users/frizop/.gem/ruby/2.1.0
        RUBYLIB		/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib
        PATH		/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bin:/usr/local/var/rbenv/versions/2.1.3/bin:/usr/local/Cellar/rbenv/0.4.0/libexec:/usr/local/var/rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
        home		/Users/frizop
    Failed running the test suite.

**Comment by electrical** [comment]
Hi,

the serverspec/specinfra stuff is hacked into beaker-rspec and by the looks of it you are purely running beaker.
Could you try to run with beaker-rspec?
`bundler exec rspec spec/acceptance/abs_spec.rb`  might work.

**Comment by frizop** [comment]
just the rspec: https://gist.github.com/frizop/51b52ce2216f5c336154 
I also tried rspec with the config: foss, https://gist.github.com/1fcfc015f83deb899d18

Also, for clarification: my gemfile has these two entries:

    gem 'beaker', :path => '/Users/frizop/Documents/src/ruby/beaker-2.2.0'
    gem 'beaker-rspec', :git => 'https://github.com/puppetlabs/beaker-rspec.git'

As I've had to rewrite a few parts of the beaker code for vcloud, and I don't know why I'm pulling beaker-rspec from git...

**Comment by electrical** [comment]
Okay. the second run fails because it was set to PE and you are missing some files. But that's fine.
The first run seems to be more complete.
Not sure why it fails loading the functions from stdlib though.
Could you run the test again without destroying the VM at the env ( RS_destroy=no ) and check if the stdlib module was copied over correctly?

**Comment by frizop** [comment]
Hmm, not seeing anything different after trying that option out. I did ssh into the server, see the end of the following gist: https://gist.github.com/5c5737b1fb4f0abd5bb9

Any ideas here?

**Comment by electrical** [comment]
Could you check C:/PROGRA~3/PuppetLabs/puppet/etc/modules/stdlib exists and what is in there?

Cheers.

**Comment by frizop** [comment]
Ok, so I hitup @electrical a bit on IRC and we're stumped at this point. I'm willing to gather maybe it's a issue with how the SSHD is setup on windows, but I can't prove/disprove this.

We switched over to calling `RS_destroy=no bundler exec rspec spec/acceptance/abs_spec.rb` in an attempt to get the bottom of the error. 

    Finished in 32.92 seconds (files took 7 minutes 6 seconds to load)
    0 examples, 0 failures
    /usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state': scp: C:/PROGRA~3/PuppetLabs/puppet/etc/modules/stdlib/lib/facter/facter_dot_d.rb: Permission denied (RuntimeError)

Full stacktrace found here:
https://gist.github.com/6a208a3d3dfbd9a41a3d

If anybody knows exactly how sshd needs to be setup that would be awesome. I have a `cyg_server` and `sshd` user setup, the cyg_server account has local admin rights, and can setuid.

**Comment by anodelman** [comment]
You could be running into the firewall or other security procedures?  It's really hard to say from afar.  Looks like you can only log into the host on the second try?  Is that true?

**Comment by frizop** [comment]
After spending some time with it I think it's either what @liamjbennett talks about here: http://tech.opentable.co.uk/blog/2014/09/01/testing-puppet-with-beaker-pt-dot-2-the-windows-story/ under the ssh section. Because it seemed what was happening is that only some of the files were copied over via ssh. Or some sort of access denied. I'm going to spend some time on this issue in the coming weeks but it'll be a bit. I'm going to go back to vagrant and prove a working solution there first as well.

So, I'll close this issue - thanks again for the help guys.

**Comment by liamjbennett** [comment]
@frizop Looking at the error I would be surprised if the problem was to do with the issue discussed in my blog post. There should be no issues from an ssh point of view in copying files. 

The way to test is to _destroy=no and try and scp files manually. Also try and ssh in and touch/type files in the directory. My guess at this point is there is a permissions issue in either how puppet is installed or how the modules are installed into that location.

Also is the /etc/modules directory actually created on the windows machine? I'm seen issues with that in the past also.

**Comment by frizop** [comment]
@liamjbennett when we did this the first time, we found only some of the files were copied over. Things like the manifest directory copied over but not the libs. I ended up cleaning up some stuff on my development box and reworking it, not sure why I was getting those errors but I've since started working on something else. I'll be revisiting this in a few weeks (I hope!)
