### ISSUE TITLE
issues installing puppet enterprise SUT rhel 6

### ISSUE THREAD

**Issue by dec-pupop** [puppetlabs/beaker#658]
I am having some issues getting started with Beaker, our current installation is windows server  2012 r2 standard with cygwin installed. the SUT is rhel 6

I have downloaded and successfully ran tests for puppetlabs/mysql with no errors. 

Mysql host file :

HOSTS:
  master-vm:
    roles:
      - master
    platform: el-6-x86_64
    snapshot: ssh
    hypervisor : vsphere
CONFIG:
  log_level: debug
  type: git

but when I try and do this for puppet enterprise I have the following issue which i captured in this gist  https://gist.github.com/dec-pupop/b2141355dda81708ba44

hostfile : 

HOSTS:
  master-vm:
    roles:
      - master
      - dashboard
      - database
      - agent
    platform: el-6-x86_64
    snapshot: ssh
    hypervisor : vsphere
CONFIG:
  log_level: debug
  pe_dir: c:\puppet\

**Comment by anodelman** [comment]
Could you do an update to beaker-rspec 5.0.1 - the windows serverspec support in beaker-rspec 5.0.0 was busted.

**Comment by anodelman** [comment]
Hm yeah, and the failure of the puppet server to start could indicate that your master node is underpowered, I've had that happen on low memory/low cpu test boxes.

**Comment by dec-pupop** [comment]
I have upgraded puppet-rspec to 5.0.1 and upgraded memory to 12gb and cpus to 4,

I am still getting the same error, looking through the log i supplied in the gist, I notice when the environment file is being set up it references ruby. I have had ruby installed previously but all foss tests failed until I removed it. does the rhel vm need ruby install on it and if yes what version?

the environment file created by beaker looks like : 

RUBYLIB=
PATH=/opt/puppet/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/vmware/bin

**Comment by electrical** [comment]
Standard ruby should be more than enough. that's what i use on my test hosts.
But it seems ruby is installed just fine but the 'puppet master service' failed to start.
Best to login after its been provisioned and see why it won't startup.

**Comment by dec-pupop** [comment]
when I execute : 

[root@master-vm ~]# service pe-httpd start
Starting pe-httpd: no listening sockets available, shutting down
Unable to open logs
                                                           [FAILED]
[root@master-vm ~]#

I don't see any logs created in   /var/log/pe-httpd/ or /var/log/pe-console-services/

**Comment by electrical** [comment]
hmm okay. open file limit issue or something like that?

**Comment by dec-pupop** [comment]
I don't know what is causing it not to start. is this an issue you have encountered before?

i would imagine a simple reboot should clear any open file limit issue.

**Comment by electrical** [comment]
I must admit i've never seen this issue with pe-httpd.

**Comment by dec-pupop** [comment]
is there any good beaker vagrant examples with either centos or rhel 6. I can take a look at the initial vagrant box set up and see if that runs sucessfully locally I guess.

**Comment by anodelman** [comment]
The 

 Starting pe-httpd: no listening sockets available, shutting down

Could indicate that the port requested by pe-httpd is already in use.  Is apache also running?

**Comment by dec-pupop** [comment]
No there is no apache running on this vm. this is a completely clean vm.

where is the setting stored to tell pe-httpd to use a specific port, I can try changing it and seeing if that work.

**Comment by anodelman** [comment]
https://docs.puppetlabs.com/pe/latest/console_config.html

**Comment by dec-pupop** [comment]
it seem thats /etc/puppetlabs/httpd/conf.d/puppetdashboard.conf was empty,
so this was the issue, also /opt/puppet/share/puppet-dashboard/certs/pe-internal-dashboard.cert.pem does not exist.

seems the installation was not complete.

**Comment by dec-pupop** [comment]
I tried an older version of puppet 3.3.1 this got me a bit further, seems now I am onto a new error on the windows side though. 

Question about cygwin on windows, should its directory be in path so commands are accessible from standard cmd?

I have an updated gist for this : 
https://gist.github.com/dec-pupop/2557d1a99b0f46e2f573

you'll see it fails on the windows when it issues commands : 

master-vm-win 03:52:32$ cd C:/cygwin64/tmp/2015-02-02_03.51.10.DCr1aJ && cmd /C 'start /w msiexec.exe /qn /L*V 2015-02-02_03.51.10.DCr1aJ.log /i puppet-enterprise-3.3.1.msi PUPPET_MASTER_SERVER=master-vm PUPPET_AGENT_CERTNAME=master-vm-win'
[00;00m[00;37m
master-vm-win executed in 0.25 seconds
[00;00m[00;37m
master-vm-win 03:52:32$ cmd.exe /c puppet agent --configprint node_name_value
[00;00m[01;30m'puppet' is not recognized as an internal or external command,

operable program or batch file.

[00;00m[00;37m

any suggestions for this?

**Comment by anodelman** [comment]
This has been followed up over email.

Closing.
