### ISSUE TITLE
Default AIO puppetpath should be /etc/puppetlabs/agent

### ISSUE THREAD

**Issue by johnduarte** [puppetlabs/beaker#660]
As of 5b050f6ccff, the default AIO puppetpath is set to /opt/puppetlabs/agent for unix. This value should be /etc/puppetlabs/agent

**Comment by anodelman** [comment]
Please file this in Jira.

**Comment by anodelman** [comment]
Ah, you already have a patch.  Leave this as-is then.  :)

**Comment by anodelman** [comment]
Merged.
