### ISSUE TITLE
Openstack support lacks region support

### ISSUE THREAD

**Issue by fiddyspence** [puppetlabs/beaker#680]
When using beaker with a multi-region Openstack, we need to pass this through to Fog, else it errors with:

    Multiple regions available choose one of these 'emea1,amers1,amers2,amers3'

**Comment by anodelman** [comment]
In PR, https://github.com/puppetlabs/beaker/pull/681

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-27
