### ISSUE TITLE
Color Output yields invisible text

### ISSUE THREAD

**Issue by grubernaut** [puppetlabs/beaker#682]
With a nodeset config of: 
```
CONFIG:
  log_level: verbose
```
The output in stdout is colored the same color as my terminal background. This is not due to the color of my terminal background, nor due to the terminal emulator program as this problem can be reproduced cross-platform and is terminal emulator agnostic.

Here is the output of the puppetlabs-java module installation with the above nodeset configuration, as displayed in my terminal:
![color_on](https://cloud.githubusercontent.com/assets/3082319/6150656/a3d810f2-b1de-11e4-8f76-837bffd051ef.png)

If I change my nodeset config to:
```
CONFIG:
  log_level: verbose
  color: false
```
Color is then disabled (not ideal), but allows the output to be shown as displayed here:
![color_off](https://cloud.githubusercontent.com/assets/3082319/6150761/47d2143c-b1df-11e4-930e-17a8afddd798.png)

This also happens regardless of which rake task you use. A custom ":acceptance" task as shown [here](https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/Rakefile#L35), or if you run the rake task that is shipped with [Puppetlabs_Spec_Helper](https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/rake_tasks.rb#L14)

I have included a map of my terminal color outputs to match up how they corrolate to the colors that are being set in [beaker/logger.rb](https://github.com/puppetlabs/beaker/blob/master/lib/beaker/logger.rb#L11)

![colors_dark](https://cloud.githubusercontent.com/assets/3082319/6151382/4e6e7d36-b1e3-11e4-8896-13c69bf3b0f3.png)

And here is the script used to generate those colors:
```bash
#!/usr/bin/bash
#

T='gYw'   # The test text

echo -e "\n                 40m     41m     42m     43m\
     44m     45m     46m     47m";

for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
           '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
           '  36m' '1;36m' '  37m' '1;37m';
  do FG=${FGs// /}
  echo -en " $FGs \033[$FG  $T  "
  for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
    do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
  done
  echo;
done
echo
```

**Comment by waynr** [comment]
For what it's worth, this has been troubling members of the classifier team: puppetlabs/ci-job-configs#85
ping @pcarlisle 

@grubernaut Just FYI, beaker does have a `--no-color` option that can be passed to it, if that helps.

**Comment by grubernaut** [comment]
@waynr luckily @garethr pointed me to that, and a way to set the no color option shown above. Before that, it wasn't all that fun :)

**Comment by garethr** [comment]
Worth noticing that (I think) this is a problem for people using Solarized (http://ethanschoonover.com/solarized) which is super possible.

**Comment by grubernaut** [comment]
![konsole_output](https://cloud.githubusercontent.com/assets/3082319/6151643/30e086b8-b1e5-11e4-9b05-b8bea69205ac.png)
I would have to agree. The above is output from a fresh install of Konsole without any configuration added. I would think that this problem would only exist for solarized dark then?

**Comment by anodelman** [comment]
I run solarized dark and do not have trouble viewing beaker output.  Weird.

**Comment by alexjfisher** [comment]
I get this problem too when using putty.  My 'solution' was to reconfigure 'ANSI black' in putty to be a bright purple colour! :)

**Comment by grubernaut** [comment]
Ah, yeah that worked for me as well @alexjfisher. 
With Urxvt I was able to set `*color_8:` to a different color, thus allowing me to see colored output from beaker.

**Comment by anodelman** [comment]
This might be best as a warning in the Beaker docs + recommended workaround.

**Comment by anodelman** [comment]
Pending action: update docs.

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-24
