### ISSUE TITLE
install_puppet methods do not support installing puppet server

### ISSUE THREAD

**Issue by liamjbennett** [puppetlabs/beaker#690]
I can see from the codebase that there has been some work done for the PE installation with puppet server but the ```install_puppet``` method which is used primarily for install FOSS does not include support for installing puppetserver.

**Comment by anodelman** [comment]
Let me talk to the FOSS guys about how this works and get back to you.

**Comment by anodelman** [comment]
So, for foss puppet we have a pre-suite test that does this:

https://github.com/puppetlabs/puppet/blob/master/acceptance/setup/aio/pre-suite/010_Install.rb#L16

You could do something similar in beaker/beaker-rspec by forcing a pre-suite step or augmenting your spec_helper_acceptance file.

**Comment by anodelman** [comment]
Closing this out.  If you have further questions please file in the jira beaker ticker tracker:

https://tickets.puppetlabs.com/issues/?jql=project%20%3D%20BKR
