### ISSUE TITLE
Unable to set docker_options in order to override read_timeout

### ISSUE THREAD

**Issue by madAndroid** [puppetlabs/beaker#700]
I can't seem to see any obvious way of overriding the docker options such as `:read_timeout`.
In the code there is a section which ensures that `::Docker.config` options are not overwritten if they already exist => (from [docker.rb](https://github.com/puppetlabs/beaker/blob/master/lib/beaker/hypervisor/docker.rb#L11))
```
 ::Docker.options = { :write_timeout => 300, :read_timeout => 300 }.merge(::Docker.options || {})
```

... but I can't see a (simple?) way of setting those config options - am I missing something?

Ideally, I'd like to add a `docker_options` line to the nodeset yaml to be able to override those default options, but that doesn't seem to work, as far as I can tell.

**Comment by anodelman** [comment]
Merged, https://github.com/puppetlabs/beaker/pull/706.
