### ISSUE TITLE
how can i test hiera roles using beaker?

### ISSUE THREAD

**Issue by developerinlondon** [puppetlabs/beaker#731]
whats the best way to test specific hiera roles using puppet beaker? i would rather load up the particular hiera role in question then to have to specify all the settings manually inside my tests.

is there any examples for this?

**Comment by electrical** [comment]
Hi,

We recently added support in beaker to make it easier to manage the hiera.yaml file and hieradata directory.
In my module [here](https://github.com/elasticsearch/puppet-elasticsearch) i make use of them.
The `copy_hiera_data_to` function allows to transfer hiera files from the repo to the host. See [here](https://github.com/elasticsearch/puppet-elasticsearch/blob/master/spec/spec_helper_acceptance.rb#L85)
The `write_hiera_config` function writes out the hiera config file. As argument you can supply the hierarchy.
In an example file [here](https://github.com/elasticsearch/puppet-elasticsearch/blob/master/spec/acceptance/014_hiera_spec.rb) I use that function several times to write a new config and set a new hiera file to be processed.

I hope this helps with your question?

**Comment by anodelman** [comment]
This would be a better topic for the google group - https://groups.google.com/forum/#!forum/puppet-beaker

Otherwise, I think that @electrical has given a good reply so closing out.
